version: '3.2'
services:
  my_website:
    hostname: my_website
    container_name: my_website
    build:
      context: .
      dockerfile: Dockerfile
    expose:
     - "80"
    ports:
     - "80:80"
